
- name: Ensure Python{{ python_version }} is installed.
  package:
    name: "python{{ python_version }}"
    state: present
  become: true

- name: Ensure Pip is installed. ( {{ pip_package }})
  package:
    name: "{{ pip_package }}"
    state: present
  become: true

- name: Ensure pip_install_packages are installed. ( {{ pip_install_packages }})
  pip:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default(omit) }}"
    virtualenv: "{{ item.virtualenv | default(omit) }}"
    state: "{{ item.state | default(omit) }}"
    executable: "{{ pip_executable }}"
  with_items: "{{ pip_install_packages }}"
  become: true
